import { TV, Technology, Room } from '@/types';

// Updated with actual Prime Day 2025 TV deals
// Note: Replace 'YOUR-AFFILIATE-TAG' with your actual Amazon Associates tag
const AFFILIATE_TAG = 'YOUR-AFFILIATE-TAG';

export const tvDeals: TV[] = [
  {
    id: 'lg-c4-48-oled',
    name: 'LG C4 OLED evo',
    brand: 'LG',
    model: 'OLED48C4PUA',
    size: 48,
    technology: 'OLED',
    currentPrice: 999,
    originalPrice: 1599,
    discount: 38,
    rating: 4.5,
    // reviewCount: TODO - check Amazon page,
    features: ['4K 120Hz', 'G-Sync/FreeSync', 'WebOS 24', 'Dolby Vision/Atmos'],
    dealRating: 'excellent',
    highlights: ['2024 Model', 'Perfect for gaming', 'Self-lit pixels', 'AI-powered processor'],
    affiliateUrl: `https://www.amazon.com/dp/B0CVR1J91Z?tag=${AFFILIATE_TAG}`,
  },
  {
    id: 'samsung-s90d-55-oled',
    name: 'Samsung S90D OLED',
    brand: 'Samsung',
    model: 'QN55S90D',
    size: 55,
    technology: 'OLED',
    currentPrice: 1297,
    originalPrice: 1997,
    discount: 35,
    rating: 4.6,
    // reviewCount: TODO - check Amazon page,
    features: ['4K 144Hz', 'Quantum HDR OLED', 'Gaming Hub', 'Tizen OS'],
    dealRating: 'excellent',
    highlights: ['2024 flagship', 'Incredible blacks', 'Samsung Gaming Hub', 'Ultra-thin design'],
    affiliateUrl: `https://www.amazon.com/dp/B0CVM8TXMJ?tag=${AFFILIATE_TAG}`,
  },
  {
    id: 'sony-bravia-8-65',
    name: 'Sony BRAVIA 8 OLED',
    brand: 'Sony',
    model: 'K65XR80',
    size: 65,
    technology: 'OLED',
    currentPrice: 1698,
    originalPrice: 2498,
    discount: 32,
    rating: 4.7,
    // reviewCount: TODO - check Amazon page,
    features: ['XR Processor', 'Acoustic Surface Audio+', 'Google TV', 'PS5 Optimized'],
    dealRating: 'excellent',
    highlights: ['Cinema quality', 'Screen is the speaker', 'PlayStation 5 features', 'IMAX Enhanced'],
    affiliateUrl: `https://www.amazon.com/dp/B0CX2X5QWP?tag=${AFFILIATE_TAG}`,
  },
  {
    id: 'tcl-qm8-65',
    name: 'TCL QM8 Mini-LED',
    brand: 'TCL',
    model: '65QM850G',
    size: 65,
    technology: 'Mini-LED',
    currentPrice: 897,
    originalPrice: 1499,
    discount: 40,
    rating: 4.4,
    // reviewCount: TODO - check Amazon page,
    features: ['Mini-LED QLED', '144Hz VRR', 'Google TV', '2000+ nits'],
    dealRating: 'excellent',
    highlights: ['Incredible brightness', 'Great for gaming', 'Quantum Dot color', 'Amazing value'],
    affiliateUrl: `https://www.amazon.com/dp/B0C78VXY5B?tag=${AFFILIATE_TAG}`,
  },
  {
    id: 'hisense-u8n-75',
    name: 'Hisense U8N Mini-LED',
    brand: 'Hisense',
    model: '75U8N',
    size: 75,
    technology: 'Mini-LED',
    currentPrice: 1398,
    originalPrice: 2199,
    discount: 36,
    rating: 4.5,
    // reviewCount: TODO - check Amazon page,
    features: ['Mini-LED ULED', '144Hz Gaming', 'Google TV', 'Dolby Vision IQ'],
    dealRating: 'excellent',
    highlights: ['3000 nits peak brightness', 'Local dimming zones', 'Game Mode Pro', 'Wi-Fi 6E'],
    affiliateUrl: `https://www.amazon.com/dp/B0CY4X8QZW?tag=${AFFILIATE_TAG}`,
  },
  {
    id: 'amazon-fire-omni-55',
    name: 'Amazon Fire TV Omni QLED',
    brand: 'Amazon',
    model: '55-inch Omni QLED',
    size: 55,
    technology: 'QLED',
    currentPrice: 419,
    originalPrice: 599,
    discount: 30,
    rating: 4.3,
    // reviewCount: TODO - check Amazon page,
    features: ['4K QLED', 'Dolby Vision IQ', 'Hands-free Alexa', 'Fire TV built-in'],
    dealRating: 'good',
    highlights: ['Adaptive brightness', 'Alexa built-in', 'Great smart features', 'Solid picture quality'],
    affiliateUrl: `https://www.amazon.com/dp/B09N6Y5BTL?tag=${AFFILIATE_TAG}`,
  },
  {
    id: 'samsung-qn90d-65',
    name: 'Samsung QN90D Neo QLED',
    brand: 'Samsung',
    model: 'QN65QN90D',
    size: 65,
    technology: 'Mini-LED',
    currentPrice: 1497,
    originalPrice: 2197,
    discount: 32,
    rating: 4.6,
    // reviewCount: TODO - check Amazon page,
    features: ['Neo QLED', '4K 120Hz', 'Anti-glare', 'Object Tracking Sound+'],
    dealRating: 'excellent',
    highlights: ['Bright room champion', 'Anti-reflective coating', 'Neural Quantum Processor', 'One Connect Box'],
    affiliateUrl: `https://www.amazon.com/dp/B0CV9N8NZB?tag=${AFFILIATE_TAG}`,
  },
  {
    id: 'lg-g4-55-oled',
    name: 'LG G4 OLED evo',
    brand: 'LG',
    model: 'OLED55G4PUA',
    size: 55,
    technology: 'OLED',
    currentPrice: 1896,
    originalPrice: 2596,
    discount: 27,
    rating: 4.8,
    // reviewCount: TODO - check Amazon page,
    features: ['MLA OLED', 'α11 AI Processor', '144Hz', 'Brightness Booster Max'],
    dealRating: 'good',
    highlights: ['Brightest OLED ever', 'Gallery design', '5-year panel warranty', 'Reference quality'],
    affiliateUrl: `https://www.amazon.com/dp/B0CVRDK6GF?tag=${AFFILIATE_TAG}`,
  },
  {
    id: 'vizio-quantum-pro-75',
    name: 'VIZIO Quantum Pro',
    brand: 'VIZIO',
    model: 'VQP75C-84',
    size: 75,
    technology: 'QLED',
    currentPrice: 898,
    originalPrice: 1298,
    discount: 31,
    rating: 4.2,
    // reviewCount: TODO - check Amazon page,
    features: ['Quantum Color', '120Hz VRR', 'SmartCast', 'Local Dimming'],
    dealRating: 'good',
    highlights: ['Great gaming TV', 'Excellent value', 'Wide color gamut', 'Low input lag'],
    affiliateUrl: `https://www.amazon.com/dp/B0CTQKVX23?tag=${AFFILIATE_TAG}`,
  },
  {
    id: 'roku-plus-series-55',
    name: 'Roku Plus Series QLED',
    brand: 'Roku',
    model: '55R6A5R',
    size: 55,
    technology: 'QLED',
    currentPrice: 399,
    originalPrice: 499,
    discount: 20,
    rating: 4.4,
    // reviewCount: TODO - check Amazon page,
    features: ['4K QLED', 'Dolby Vision', 'Roku Smart TV', 'Local Dimming'],
    dealRating: 'good',
    highlights: ['Roku interface', 'Great smart features', 'Solid picture', 'Budget QLED option'],
    affiliateUrl: `https://www.amazon.com/dp/B0C74MRJ23?tag=${AFFILIATE_TAG}`,
  },
  {
    id: 'insignia-f30-50',
    name: 'Insignia F30 Fire TV',
    brand: 'Insignia',
    model: 'NS-50F301NA24',
    size: 50,
    technology: 'LED',
    currentPrice: 189,
    originalPrice: 299,
    discount: 37,
    rating: 4.1,
    // reviewCount: TODO - check Amazon page,
    features: ['4K LED', 'Fire TV', 'DTS Studio Sound', 'Alexa Voice Remote'],
    dealRating: 'excellent',
    highlights: ['Unbeatable price', 'Fire TV built-in', '4K resolution', 'Perfect for bedrooms'],
    affiliateUrl: `https://www.amazon.com/dp/B0B3GZ7XM9?tag=${AFFILIATE_TAG}`,
  },
  {
    id: 'toshiba-c350-65',
    name: 'Toshiba C350 Fire TV',
    brand: 'Toshiba',
    model: '65C350LU',
    size: 65,
    technology: 'LED',
    currentPrice: 369,
    originalPrice: 529,
    discount: 30,
    rating: 4.2,
    // reviewCount: TODO - check Amazon page,
    features: ['4K LED', 'Fire TV', 'Dolby Vision', 'DTS Virtual:X'],
    dealRating: 'good',
    highlights: ['Large screen value', 'Regza Engine', 'Gaming mode', 'Hands-free Alexa'],
    affiliateUrl: `https://www.amazon.com/dp/B0C1J8QK6Y?tag=${AFFILIATE_TAG}`,
  },
];

export const technologies: Technology[] = [
  {
    id: 'oled',
    name: 'OLED',
    description: 'Self-emitting pixels for perfect blacks',
    pros: ['Perfect blacks', 'Infinite contrast', 'Wide viewing angles', 'Fast response time'],
    cons: ['Risk of burn-in', 'Less bright than LED', 'More expensive'],
    priceRange: { min: 599, max: 3000 },
    bestFor: 'Dark room viewing, movies, gaming',
    metrics: {
      contrast: 100,
      brightness: 70,
      color: 95,
    },
  },
  {
    id: 'qd-oled',
    name: 'QD-OLED',
    description: 'OLED enhanced with Quantum Dots',
    pros: ['Best color accuracy', 'Brighter than OLED', 'Perfect blacks', 'No burn-in'],
    cons: ['Most expensive', 'Limited availability'],
    priceRange: { min: 1500, max: 4500 },
    bestFor: 'Ultimate picture quality seekers',
    metrics: {
      contrast: 100,
      brightness: 90,
      color: 100,
    },
  },
  {
    id: 'mini-led',
    name: 'Mini-LED',
    description: 'Thousands of tiny LEDs for better control',
    pros: ['Very bright', 'Great contrast', 'No burn-in', 'Good value'],
    cons: ['Some blooming', 'Not as good as OLED blacks'],
    priceRange: { min: 700, max: 2500 },
    bestFor: 'Bright rooms, HDR content, gaming',
    metrics: {
      contrast: 85,
      brightness: 95,
      color: 90,
    },
  },
  {
    id: 'qled',
    name: 'QLED',
    description: 'Quantum Dot enhanced LED',
    pros: ['Very bright', 'Good colors', 'Affordable', 'No burn-in'],
    cons: ['Poor black levels', 'Limited viewing angles'],
    priceRange: { min: 300, max: 1500 },
    bestFor: 'Bright rooms, budget conscious',
    metrics: {
      contrast: 60,
      brightness: 90,
      color: 80,
    },
  },
  {
    id: 'led',
    name: 'LED',
    description: 'Traditional LCD with LED backlight',
    pros: ['Most affordable', 'Reliable', 'Energy efficient'],
    cons: ['Basic picture quality', 'Poor contrast', 'Limited colors'],
    priceRange: { min: 150, max: 600 },
    bestFor: 'Basic viewing, tight budgets',
    metrics: {
      contrast: 40,
      brightness: 75,
      color: 60,
    },
  },
];

export const roomDesigns: Room[] = [
  {
    id: 'modern-minimal',
    name: 'Sleek Modern Living Room with Hidden TV',
    style: 'modern',
    description: 'Clean lines meet cutting-edge tech. This serene space centers around the stunning Samsung S90D OLED.',
    totalBudget: 2800,
    featuredTV: tvDeals[1], // Samsung S90D OLED
    furniture: [
      { id: 'sofa-1', name: 'Rivet Revolve Modern Sofa', price: 899, category: 'seating', affiliateUrl: `https://www.amazon.com/dp/B07DHP6ZGY?tag=${AFFILIATE_TAG}` },
      { id: 'lamp-1', name: 'Brightech Sky LED Arc Lamp', price: 129, category: 'lighting', affiliateUrl: `https://www.amazon.com/dp/B01A8FIQK8?tag=${AFFILIATE_TAG}` },
      { id: 'table-1', name: 'Nathan James Theo Coffee Table', price: 249, category: 'tables', affiliateUrl: `https://www.amazon.com/dp/B07HKK9ZPX?tag=${AFFILIATE_TAG}` },
    ],
    saves: 12300,
  },
  {
    id: 'cozy-cottage',
    name: 'Warm & Cozy TV Room for Family Movie Nights',
    style: 'cozy',
    description: 'Warm and inviting space perfect for movie nights. Features the incredible Sony BRAVIA 8 OLED.',
    totalBudget: 3200,
    featuredTV: tvDeals[2], // Sony BRAVIA 8
    furniture: [
      { id: 'sofa-2', name: 'Stone & Beam Lauren Sofa', price: 1095, category: 'seating', affiliateUrl: `https://www.amazon.com/dp/B072QTNWL3?tag=${AFFILIATE_TAG}` },
      { id: 'lamp-2', name: 'DEWENWILS Table Lamp Set', price: 89, category: 'lighting', affiliateUrl: `https://www.amazon.com/dp/B07L8R5678?tag=${AFFILIATE_TAG}` },
      { id: 'table-2', name: 'Walker Edison Modern Farmhouse Table', price: 289, category: 'tables', affiliateUrl: `https://www.amazon.com/dp/B07MX2NYBF?tag=${AFFILIATE_TAG}` },
    ],
    saves: 18700,
  },
  {
    id: 'budget-modern',
    name: 'Minimalist Apartment Living Room Under $2K',
    style: 'minimal',
    description: 'Amazing value without compromise. The TCL QM8 Mini-LED delivers premium features at a great price.',
    totalBudget: 1600,
    featuredTV: tvDeals[3], // TCL QM8
    furniture: [
      { id: 'sofa-3', name: 'Zinus Jackie Classic Sofa', price: 379, category: 'seating', affiliateUrl: `https://www.amazon.com/dp/B078GQHT5J?tag=${AFFILIATE_TAG}` },
      { id: 'lamp-3', name: 'LEPOWER Wood Tripod Lamp', price: 59, category: 'lighting', affiliateUrl: `https://www.amazon.com/dp/B073W4HY5K?tag=${AFFILIATE_TAG}` },
      { id: 'table-3', name: 'Furinno Simple Design Table', price: 99, category: 'tables', affiliateUrl: `https://www.amazon.com/dp/B004M5BGD8?tag=${AFFILIATE_TAG}` },
    ],
    saves: 28100,
  },
  {
    id: 'gaming-paradise',
    name: 'RGB Gaming Room Setup with OLED Display',
    style: 'modern',
    description: 'Built for gamers. The LG C4 OLED with 120Hz and G-Sync delivers the ultimate gaming experience.',
    totalBudget: 2200,
    featuredTV: tvDeals[0], // LG C4 OLED
    furniture: [
      { id: 'sofa-4', name: 'GTRACING Gaming Sofa', price: 499, category: 'seating', affiliateUrl: `https://www.amazon.com/dp/B088KXCSJN?tag=${AFFILIATE_TAG}` },
      { id: 'lamp-4', name: 'Govee Immersion LED Light Bars', price: 149, category: 'lighting', affiliateUrl: `https://www.amazon.com/dp/B09CLP9DXC?tag=${AFFILIATE_TAG}` },
      { id: 'table-4', name: 'Rolanstar Coffee Table with LED', price: 189, category: 'tables', affiliateUrl: `https://www.amazon.com/dp/B099K2RWKY?tag=${AFFILIATE_TAG}` },
    ],
    saves: 16200,
  },
  {
    id: 'luxury-theater',
    name: 'Luxury Home Theater with 75" Screen',
    style: 'luxury',
    description: 'No compromise home theater. The massive Hisense U8N 75" Mini-LED creates a true cinema experience.',
    totalBudget: 3500,
    featuredTV: tvDeals[4], // Hisense U8N 75"
    furniture: [
      { id: 'sofa-5', name: 'Ashley Furniture Signature Sectional', price: 1299, category: 'seating', affiliateUrl: `https://www.amazon.com/dp/B07J5S888Y?tag=${AFFILIATE_TAG}` },
      { id: 'lamp-5', name: 'Philips Hue Go Portable Light', price: 159, category: 'lighting', affiliateUrl: `https://www.amazon.com/dp/B08G4DQWDS?tag=${AFFILIATE_TAG}` },
      { id: 'table-5', name: 'WLIVE LED Coffee Table', price: 279, category: 'tables', affiliateUrl: `https://www.amazon.com/dp/B0B1HQSG5K?tag=${AFFILIATE_TAG}` },
    ],
    saves: 9200,
  },
  {
    id: 'small-space',
    name: 'Small Apartment Living Room TV Setup',
    style: 'minimal',
    description: 'Perfect for apartments. The Amazon Fire TV Omni QLED combines great picture quality with Alexa integration.',
    totalBudget: 1100,
    featuredTV: tvDeals[5], // Amazon Fire TV Omni
    furniture: [
      { id: 'sofa-6', name: 'DHP Emily Futon Couch', price: 299, category: 'seating', affiliateUrl: `https://www.amazon.com/dp/B01M0A4B9M?tag=${AFFILIATE_TAG}` },
      { id: 'lamp-6', name: 'TaoTronics LED Desk Lamp', price: 39, category: 'lighting', affiliateUrl: `https://www.amazon.com/dp/B07CWLBVL7?tag=${AFFILIATE_TAG}` },
      { id: 'table-6', name: 'VASAGLE Nesting Coffee Table', price: 129, category: 'tables', affiliateUrl: `https://www.amazon.com/dp/B07K8TJ3R6?tag=${AFFILIATE_TAG}` },
    ],
    saves: 34300,
  },
];