import { TV, Technology, Room } from '@/types';

// Updated with actual Prime Day 2025 TV deals
// Note: Replace 'YOUR-AFFILIATE-TAG' with your actual Amazon Associates tag
const AFFILIATE_TAG = process.env.NEXT_PUBLIC_AMAZON_AFFILIATE_TAG || 'YOUR-AFFILIATE-TAG';

export const tvDeals: TV[] = [
  {
    id: 'hisense-B0DYWNQMQJ',
    name: 'Hisense 75" Class U6 Series Mini-LED 4K UHD Smart Fire TV...',
    brand: 'Hisense',
    model: 'B0DYWNQMQJ',
    size: 75,
    technology: 'QLED',
    currentPrice: 799,
    originalPrice: 1299.99,
    discount: 39,
    rating: 4.4,
    reviewCount: 87,
    features: ['4K UHD', 'Smart TV', 'HDR', 'Dolby Vision/Atmos'],
    dealRating: 'excellent',
    highlights: ['Previously viewed', 'Save 39%', 'Large Screen', 'Quantum Colors'],
    affiliateUrl: `https://www.amazon.com/dp/B0DYWNQMQJ?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/81+DLdRTgnL._AC_UY218_.jpg',
  },
  {
    id: 'hisense-B0DYVRJJY4',
    name: 'Hisense 50" Class QD7 Series Mini-LED 4K UHD Smart Fire T...',
    brand: 'Hisense',
    model: 'B0DYVRJJY4',
    size: 50,
    technology: 'QLED',
    currentPrice: 329,
    originalPrice: 399.99,
    discount: 18,
    rating: 4.4,
    reviewCount: 125,
    features: ['4K UHD', 'Smart TV', 'HDR', 'Dolby Vision/Atmos'],
    dealRating: 'fair',
    highlights: ['Previously viewed', 'Save 18%', 'Quantum Colors'],
    affiliateUrl: `https://www.amazon.com/dp/B0DYVRJJY4?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/81iAxUxBDYL._AC_UY218_.jpg',
  },
  {
    id: 'amazon-B0CZBLZYY5',
    name: 'Amazon Fire TV 50" 4-Series 4K UHD smart TV, stream live ...',
    brand: 'Amazon',
    model: 'B0CZBLZYY5',
    size: 50,
    technology: 'LED',
    currentPrice: 259,
    originalPrice: 399.99,
    discount: 35,
    rating: 4.4,
    reviewCount: 783,
    features: ['4K UHD'],
    dealRating: 'excellent',
    highlights: ['Previously viewed', 'Save 35%'],
    affiliateUrl: `https://www.amazon.com/dp/B0CZBLZYY5?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/71ka3DKN63L._AC_UY218_.jpg',
  },
  {
    id: 'insignia-B0DM2LQV3F',
    name: 'INSIGNIA 65-inch Class F50 Series LED 4K UHD Smart Fire T...',
    brand: 'Insignia',
    model: 'B0DM2LQV3F',
    size: 65,
    technology: 'LED',
    currentPrice: 279,
    originalPrice: 449.99,
    discount: 38,
    rating: 4.5,
    reviewCount: 485,
    features: ['4K UHD', 'Smart TV'],
    dealRating: 'excellent',
    highlights: ['Prime Day Deal', 'Save 38%', 'Large Screen'],
    affiliateUrl: `https://www.amazon.com/dp/B0DM2LQV3F?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/710gREHO2FL._AC_UY218_.jpg',
  },
  {
    id: 'lg-B0CVS18PH9',
    name: 'LG 65-Inch Class OLED evo C4 Series Smart TV 4K Processor...',
    brand: 'Lg',
    model: 'B0CVS18PH9',
    size: 65,
    technology: 'OLED',
    currentPrice: 1196,
    originalPrice: 1326.99,
    discount: 10,
    rating: 4.5,
    reviewCount: 1,
    features: ['4K UHD', 'Smart TV'],
    dealRating: 'fair',
    highlights: ['Prime Day Deal', 'Save 10%', 'Large Screen', 'Premium Display'],
    affiliateUrl: `https://www.amazon.com/dp/B0CVS18PH9?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/81QAq0+lmxL._AC_UY218_.jpg',
  },
  {
    id: 'hisense-B0DYWG3BL1',
    name: 'Hisense 55" Class U6 Series Mini-LED 4K UHD Smart Fire TV...',
    brand: 'Hisense',
    model: 'B0DYWG3BL1',
    size: 55,
    technology: 'QLED',
    currentPrice: 447,
    originalPrice: 799.99,
    discount: 44,
    rating: 4.4,
    reviewCount: 87,
    features: ['4K UHD', 'Smart TV', 'HDR', 'Dolby Vision/Atmos'],
    dealRating: 'excellent',
    highlights: ['Previously viewed', 'Save 44%', 'Quantum Colors'],
    affiliateUrl: `https://www.amazon.com/dp/B0DYWG3BL1?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/81Jss7GPQcL._AC_UY218_.jpg',
  },
  {
    id: 'hisense-B0F9LRX1LY',
    name: 'Hisense 98" Class QD5 Series (98QD5QG, 2025 Model) QLED 4...',
    brand: 'Hisense',
    model: 'B0F9LRX1LY',
    size: 98,
    technology: 'QLED',
    currentPrice: 1499,
    originalPrice: 2298,
    discount: 35,
    rating: 1,
    reviewCount: 1,
    features: ['4K UHD', 'Smart TV', 'HDR', 'Dolby Vision/Atmos'],
    dealRating: 'excellent',
    highlights: ['Previously viewed', 'Save 35%', 'Large Screen', 'Quantum Colors'],
    affiliateUrl: `https://www.amazon.com/dp/B0F9LRX1LY?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/81qLYWQDRNL._AC_UY218_.jpg',
  },
  {
    id: 'samsung-B0DXMWL3RW',
    name: 'Samsung 65-Inch Class Crystal UHD U8000F 4K Smart TV (202...',
    brand: 'Samsung',
    model: 'B0DXMWL3RW',
    size: 65,
    technology: 'LED',
    currentPrice: 457,
    originalPrice: 497.99,
    discount: 8,
    rating: 4.1,
    reviewCount: 240,
    features: ['4K UHD', 'Smart TV'],
    dealRating: 'fair',
    highlights: ['Previously viewed', 'Save 8%', 'Large Screen'],
    affiliateUrl: `https://www.amazon.com/dp/B0DXMWL3RW?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/81g6xeGzK2L._AC_UY218_.jpg',
  },
  {
    id: 'roku-B0DWHKF7V5',
    name: 'Roku Smart TV 2025 – 55-Inch Select Series, 4K HDR TV – R...',
    brand: 'Roku',
    model: 'B0DWHKF7V5',
    size: 55,
    technology: 'LED',
    currentPrice: 249,
    originalPrice: 349.99,
    discount: 29,
    rating: 4.5,
    reviewCount: 295,
    features: ['4K UHD', 'Smart TV', 'HDR'],
    dealRating: 'good',
    highlights: ['Limited time deal', 'Save 29%'],
    affiliateUrl: `https://www.amazon.com/dp/B0DWHKF7V5?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/71c5T63TN6L._AC_UY218_.jpg',
  },
  {
    id: 'insignia-B0F1C232S8',
    name: 'INSIGNIA 70" Class F50 Series LED 4K UHD Smart Fire TV wi...',
    brand: 'Insignia',
    model: 'B0F1C232S8',
    size: 70,
    technology: 'LED',
    currentPrice: 329,
    originalPrice: 499.99,
    discount: 34,
    rating: 4.4,
    reviewCount: 281,
    features: ['4K UHD', 'Smart TV'],
    dealRating: 'excellent',
    highlights: ['Previously viewed', 'Save 34%', 'Large Screen'],
    affiliateUrl: `https://www.amazon.com/dp/B0F1C232S8?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/81jLRWNrTXL._AC_UY218_.jpg',
  },
  {
    id: 'insignia-B0F256YJCK',
    name: 'INSIGNIA 40" Class F20 Series LED Full HD Smart Fire TV w...',
    brand: 'Insignia',
    model: 'B0F256YJCK',
    size: 40,
    technology: 'LED',
    currentPrice: 99,
    originalPrice: 149.99,
    discount: 34,
    rating: 4.1,
    reviewCount: 79,
    features: ['Smart TV'],
    dealRating: 'excellent',
    highlights: ['Prime Day Deal', 'Save 34%'],
    affiliateUrl: `https://www.amazon.com/dp/B0F256YJCK?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/81D3eudtv5L._AC_UY218_.jpg',
  },
  {
    id: 'hisense-B0F1DWQKXC',
    name: 'Hisense 65" Class U7 Mini-LED ULED 4K UHD Google Smart TV...',
    brand: 'Hisense',
    model: 'B0F1DWQKXC',
    size: 65,
    technology: 'QLED',
    currentPrice: 797,
    originalPrice: 1499.99,
    discount: 47,
    rating: 4.5,
    reviewCount: 43,
    features: ['4K UHD', 'Smart TV', 'HDR', 'Dolby Vision/Atmos'],
    dealRating: 'excellent',
    highlights: ['Previously viewed', 'Save 47%', 'Large Screen', 'Quantum Colors'],
    affiliateUrl: `https://www.amazon.com/dp/B0F1DWQKXC?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/81O2wBThNwL._AC_UY218_.jpg',
  },
  {
    id: 'samsung-B0CV9F2Q5V',
    name: 'Samsung 55-Inch Class QLED 4K LS03D The Frame Series Quan...',
    brand: 'Samsung',
    model: 'B0CV9F2Q5V',
    size: 55,
    technology: 'QLED',
    currentPrice: 797,
    originalPrice: 1497.99,
    discount: 47,
    rating: 4.1,
    reviewCount: 786,
    features: ['4K UHD', 'Smart TV', 'HDR', 'Dolby Vision/Atmos'],
    dealRating: 'excellent',
    highlights: ['Previously viewed', 'Save 47%', 'Quantum Colors'],
    affiliateUrl: `https://www.amazon.com/dp/B0CV9F2Q5V?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/71q0Zmb74pL._AC_UY218_.jpg',
  },
  {
    id: 'hisense-B0D2PNVJFT',
    name: 'Hisense 65-Inch Class QLED 4K S7N CanvasTV™ Series Dolby ...',
    brand: 'Hisense',
    model: 'B0D2PNVJFT',
    size: 65,
    technology: 'QLED',
    currentPrice: 898,
    originalPrice: 1299.99,
    discount: 31,
    rating: 4.6,
    reviewCount: 306,
    features: ['4K UHD', 'Smart TV', 'HDR', 'Dolby Vision/Atmos'],
    dealRating: 'excellent',
    highlights: ['In your list', 'Save 31%', 'Large Screen', 'Quantum Colors'],
    affiliateUrl: `https://www.amazon.com/dp/B0D2PNVJFT?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/812uGMjcZ+L._AC_UY218_.jpg',
  },
  {
    id: 'hisense-B0DYS29P6M',
    name: 'Hisense 55" Class QD6 Series (55QD6QF, 2025 Model) QLED 4...',
    brand: 'Hisense',
    model: 'B0DYS29P6M',
    size: 55,
    technology: 'QLED',
    currentPrice: 239,
    originalPrice: 379.99,
    discount: 37,
    rating: 4.1,
    reviewCount: 279,
    features: ['4K UHD', 'Smart TV', 'HDR', 'Dolby Vision/Atmos'],
    dealRating: 'excellent',
    highlights: ['Previously viewed', 'Save 37%', 'Quantum Colors'],
    affiliateUrl: `https://www.amazon.com/dp/B0DYS29P6M?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/81BbB+ji0uL._AC_UY218_.jpg',
  },
  {
    id: 'B0DYVR565M',
    name: 'Hisense 65" Class QD7 Series Mini-LED 4K UHD Smart Fire TV (65QD7QF, 2025 Model) - QLED, HDR10+, Dol',
    brand: 'Hisense',
    model: 'B0DYVR565M',
    size: 65,
    technology: 'QLED',
    currentPrice: 469,
    originalPrice: 599.99,
    discount: 22,
    rating: 4.4,
    reviewCount: 125,
    features: ['4K UHD', 'Smart TV', 'HDR', 'Dolby Vision/Atmos'],
    dealRating: 'good',
    highlights: ['Save $130.99'],
    affiliateUrl: `https://www.amazon.com/dp/B0DYVR565M?tag=${AFFILIATE_TAG}`,
    imageUrl: 'https://m.media-amazon.com/images/I/815AVndLSpL._AC_UY218_.jpg',
  },
  {
    id: "B0F433J5DZ",
    name: "65-Inch Class QLED 4K Smart TV, Ultra-Slim Mural TV, 144Hz, HDR, Art Mode w/AI Art, Wide Color Gamut",
    brand: "Unknown",
    model: "B0F433J5DZ",
    size: 65,
    technology: "QLED",
    currentPrice: 759,
    originalPrice: 999.99,
    discount: 24,
    rating: 4.4,
    reviewCount: 35,
    features: [
      "4K UHD",
      "Smart TV",
      "HDR",
      "Dolby Vision/Atmos"
    ],
    dealRating: "good",
    highlights: [
      "Save $240.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0F433J5DZ?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/81N+sCcdgkL._AC_UY218_.jpg"
  },
  {
    id: "B0CPQ6WDYH",
    name: "Toshiba 75\" Class C350 Series LED 4K UHD Smart Fire TV with Alexa Voice Remote (75C350LU, 2024 Model",
    brand: "Toshiba",
    model: "B0CPQ6WDYH",
    size: 75,
    technology: "LED",
    currentPrice: 429,
    originalPrice: 649.99,
    discount: 34,
    rating: 4.4,
    reviewCount: 4,
    features: [
      "4K UHD",
      "Smart TV"
    ],
    dealRating: "good",
    highlights: [
      "Save $220.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0CPQ6WDYH?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/61NqjgmpyEL._AC_UY218_.jpg"
  },
  {
    id: "B0DYW81FWH",
    name: "Hisense 65\" Class U6 Series Mini-LED 4K UHD Smart Fire TV (65U65QF, 2025 Model) - QLED, Native 144Hz",
    brand: "Hisense",
    model: "B0DYW81FWH",
    size: 65,
    technology: "QLED",
    currentPrice: 599,
    originalPrice: 999.99,
    discount: 40,
    rating: 4.4,
    reviewCount: 87,
    features: [
      "4K UHD",
      "Smart TV",
      "HDR",
      "Dolby Vision/Atmos"
    ],
    dealRating: "good",
    highlights: [
      "Save $400.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0DYW81FWH?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/81XMT3aZtnL._AC_UY218_.jpg"
  },
  {
    id: "B0F1DRNWP7",
    name: "Hisense 55\" Class U8 Mini-LED ULED 4K UHD Google Smart TV (55U8QG, 2025 Model) - QLED, Native 165Hz,",
    brand: "Hisense",
    model: "B0F1DRNWP7",
    size: 55,
    technology: "QLED",
    currentPrice: 878,
    originalPrice: 1499.99,
    discount: 41,
    rating: 4.5,
    reviewCount: 43,
    features: [
      "4K UHD",
      "Smart TV",
      "HDR",
      "Dolby Vision/Atmos"
    ],
    dealRating: "good",
    highlights: [
      "Save $621.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0F1DRNWP7?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/81DjhNwmYvL._AC_UY218_.jpg"
  },
  {
    id: "B0DXMT6CJP",
    name: "Samsung 65-Inch Class QLED Q7F Series Samsung Vision AI Smart TV (2025 Model, 65Q7F) Quantum HDR, Ob",
    brand: "Samsung",
    model: "B0DXMT6CJP",
    size: 65,
    technology: "QLED",
    currentPrice: 547,
    originalPrice: 627.99,
    discount: 13,
    rating: 4.2,
    reviewCount: 197,
    features: [
      "4K UHD",
      "Smart TV",
      "HDR"
    ],
    dealRating: "good",
    highlights: [
      "Save $80.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0DXMT6CJP?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/81LOXgmvLeL._AC_UY218_.jpg"
  },
  {
    id: "B0DZ8R71DB",
    name: "TOSHIBA 50\" Class C350 Series LED 4K UHD Smart Fire TV with Voice Remote with Alexa (50C350NU)",
    brand: "Toshiba",
    model: "B0DZ8R71DB",
    size: 50,
    technology: "LED",
    currentPrice: 199,
    originalPrice: 349.99,
    discount: 43,
    rating: 4.2,
    reviewCount: 165,
    features: [
      "4K UHD",
      "Smart TV"
    ],
    dealRating: "good",
    highlights: [
      "Save $150.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0DZ8R71DB?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/81GTMnklZQL._AC_UY218_.jpg"
  },
  {
    id: "B0CY4TQ91Q",
    name: "Hisense 55-Inch Class U8 Series Mini-LED ULED 4K UHD Google Smart TV (55U8N) - QLED, Dolby Vision IQ",
    brand: "Hisense",
    model: "B0CY4TQ91Q",
    size: 55,
    technology: "QLED",
    currentPrice: 648,
    originalPrice: 698,
    discount: 7,
    rating: 4.2,
    reviewCount: 801,
    features: [
      "4K UHD",
      "Smart TV",
      "Dolby Vision/Atmos"
    ],
    dealRating: "good",
    highlights: [
      "Save $50.00"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0CY4TQ91Q?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/91lwPEBtZJL._AC_UY218_.jpg"
  },
  {
    id: "B0CMDJ8TK3",
    name: "INSIGNIA 43\" Class F30 Series LED 4K UHD Smart Fire TV, Voice Remote with Alexa, Stream Live TV With",
    brand: "Insignia",
    model: "B0CMDJ8TK3",
    size: 43,
    technology: "LED",
    currentPrice: 149,
    originalPrice: 199.99,
    discount: 25,
    rating: 4.5,
    reviewCount: 2,
    features: [
      "4K UHD",
      "Smart TV"
    ],
    dealRating: "good",
    highlights: [
      "Save $50.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0CMDJ8TK3?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/81Q0HLbeLbL._AC_UY218_.jpg"
  },
  {
    id: "B0DSRSTJ54",
    name: "TCL 65-Inch Class QM6K Series QD-Mini LED 4K UHD Google Smart TV Best Value Mini-LED TV - QLED, 144h",
    brand: "Tcl",
    model: "B0DSRSTJ54",
    size: 65,
    technology: "QLED",
    currentPrice: 547,
    originalPrice: 698,
    discount: 22,
    rating: 4.4,
    reviewCount: 144,
    features: [
      "4K UHD",
      "Smart TV",
      "Dolby Vision/Atmos"
    ],
    dealRating: "good",
    highlights: [
      "Save $151.00"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0DSRSTJ54?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/71VBjJ-uQXL._AC_UY218_.jpg"
  },
  {
    id: "B0DYWG3BL1",
    name: "Hisense 55\" Class U6 Series Mini-LED 4K UHD Smart Fire TV (55U65QF, 2025 Model) - QLED, Native 144Hz",
    brand: "Hisense",
    model: "B0DYWG3BL1",
    size: 55,
    technology: "QLED",
    currentPrice: 447,
    originalPrice: 799.99,
    discount: 44,
    rating: 4.4,
    reviewCount: 87,
    features: [
      "4K UHD",
      "Smart TV",
      "HDR",
      "Dolby Vision/Atmos"
    ],
    dealRating: "good",
    highlights: [
      "Save $352.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0DYWG3BL1?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/81Jss7GPQcL._AC_UY218_.jpg"
  },
  {
    id: "B0F35W3T1C",
    name: "Hisense 85-Inch Class QLED 4K S7N CanvasTV Series Dolby Vision HDR Google Smart TV (85S7N, 2025 Mode",
    brand: "Hisense",
    model: "B0F35W3T1C",
    size: 85,
    technology: "QLED",
    currentPrice: 1997,
    originalPrice: 3999.99,
    discount: 50,
    rating: 4.6,
    reviewCount: 306,
    features: [
      "4K UHD",
      "Smart TV",
      "HDR",
      "Dolby Vision/Atmos"
    ],
    dealRating: "good",
    highlights: [
      "Save $2002.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0F35W3T1C?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/812uGMjcZ+L._AC_UY218_.jpg"
  },
  {
    id: "B0CHJ7GQ2Q",
    name: "Hisense 75” Class U6 Series ULED 4K UHD Smart Fire TV (75U6HF, 2024) - QLED, Full Array Local Dimmin",
    brand: "Hisense",
    model: "B0CHJ7GQ2Q",
    size: 55,
    technology: "QLED",
    currentPrice: 493,
    originalPrice: 529.99,
    discount: 7,
    rating: 4.2,
    reviewCount: 4,
    features: [
      "4K UHD",
      "Smart TV",
      "HDR",
      "Dolby Vision/Atmos"
    ],
    dealRating: "good",
    highlights: [
      "Save $36.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0CHJ7GQ2Q?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/71oAhtaqY1L._AC_UY218_.jpg"
  },
  {
    id: "B0D4NYW7QS",
    name: "TCL 65-Inch Class S5 UHD 4K LED Smart TV with Fire TV (65S551F, 2024 Model), Dolby Vision, HDR PRO+,",
    brand: "Tcl",
    model: "B0D4NYW7QS",
    size: 65,
    technology: "LED",
    currentPrice: 339,
    originalPrice: 449.99,
    discount: 25,
    rating: 4.1,
    reviewCount: 2,
    features: [
      "4K UHD",
      "Smart TV",
      "HDR",
      "Dolby Vision/Atmos"
    ],
    dealRating: "good",
    highlights: [
      "Save $110.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0D4NYW7QS?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/7195La7MKSL._AC_UY218_.jpg"
  },
  {
    id: "B0DVWXXRDL",
    name: "TCL 55-Inch Class QM7K Series QD-Mini LED 4K UHD Google Smart TV Best Premium Mini-LED TV - QLED, 14",
    brand: "Tcl",
    model: "B0DVWXXRDL",
    size: 55,
    technology: "QLED",
    currentPrice: 598,
    originalPrice: 1199.99,
    discount: 50,
    rating: 4,
    reviewCount: 34,
    features: [
      "4K UHD",
      "Smart TV"
    ],
    dealRating: "good",
    highlights: [
      "Save $601.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0DVWXXRDL?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/812yrdwifxL._AC_UY218_.jpg"
  },
  {
    id: "B0DXMT6YD4",
    name: "Samsung 50-Inch Class Crystal UHD U8000F 4K Smart TV (2025 Model) Endless Free Content, Crystal Proc",
    brand: "Samsung",
    model: "B0DXMT6YD4",
    size: 50,
    technology: "LED",
    currentPrice: 327,
    originalPrice: 0,
    discount: 0,
    rating: 4.1,
    reviewCount: 240,
    features: [
      "4K UHD",
      "Smart TV"
    ],
    dealRating: "good",
    highlights: [
      "Save $72.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0DXMT6YD4?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/8170FdFwkML._AC_UY218_.jpg"
  },
  {
    id: "B0CY3C6Q7K",
    name: "Samsung 85-Inch Class QLED 4K Q80D Series Quantum HDR+ Smart TV w/Dolby Atmos, Object Tracking Sound",
    brand: "Samsung",
    model: "B0CY3C6Q7K",
    size: 85,
    technology: "QLED",
    currentPrice: 1297,
    originalPrice: 2797.99,
    discount: 54,
    rating: 4.3,
    reviewCount: 302,
    features: [
      "4K UHD",
      "Smart TV",
      "HDR",
      "Dolby Vision/Atmos"
    ],
    dealRating: "good",
    highlights: [
      "Save $1500.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0CY3C6Q7K?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/61-irP7v82L._AC_UY218_.jpg"
  },
  {
    id: "B0BVMYQXGZ",
    name: "SAMSUNG 43-Inch Class Crystal UHD 4K CU8000 Series PurColor, Object Tracking Sound Lite, Q-Symphony,",
    brand: "Samsung",
    model: "B0BVMYQXGZ",
    size: 43,
    technology: "LED",
    currentPrice: 387,
    originalPrice: 0,
    discount: 0,
    rating: 4.4,
    reviewCount: 1,
    features: [
      "4K UHD",
      "Smart TV"
    ],
    dealRating: "good",
    highlights: [
      "Save $72.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0BVMYQXGZ?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/71bdeNqyARL._AC_UY218_.jpg"
  },
  {
    id: "B0CXG3HMX1",
    name: "VIZIO 40-inch Full HD 1080p Smart TV with DTS Virtual: X, Alexa Compatibility, Google Cast Built-in,",
    brand: "Vizio",
    model: "B0CXG3HMX1",
    size: 40,
    technology: "LED",
    currentPrice: 138,
    originalPrice: 169.99,
    discount: 19,
    rating: 4.1,
    reviewCount: 4,
    features: [
      "Smart TV"
    ],
    dealRating: "good",
    highlights: [
      "Save $31.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0CXG3HMX1?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/81NLMdXhvrL._AC_UY218_.jpg"
  },
  {
    id: "B0D1JH53Y7",
    name: "TCL 65-Inch Q68 QLED Pro 4K UHD Smart TV with Google TV (65Q681G, 2024 Model) Dolby Vision, Dolby At",
    brand: "Tcl",
    model: "B0D1JH53Y7",
    size: 65,
    technology: "QLED",
    currentPrice: 459,
    originalPrice: 0,
    discount: 0,
    rating: 4.3,
    reviewCount: 166,
    features: [
      "4K UHD",
      "Smart TV",
      "HDR",
      "120Hz",
      "Dolby Vision/Atmos"
    ],
    dealRating: "good",
    highlights: [
      "Save $72.99"
    ],
    affiliateUrl: `https://www.amazon.com/dp/B0D1JH53Y7?tag=${AFFILIATE_TAG}`,
    imageUrl: "https://m.media-amazon.com/images/I/81QEewnDH-L._AC_UY218_.jpg"
  }  
];

export const technologies: Technology[] = [
  {
    id: 'oled',
    name: 'OLED',
    description: 'Self-emitting pixels for perfect blacks',
    pros: ['Perfect blacks', 'Infinite contrast', 'Wide viewing angles', 'Fast response time'],
    cons: ['Risk of burn-in', 'Less bright than LED', 'More expensive'],
    priceRange: { min: 599, max: 3000 },
    bestFor: 'Dark room viewing, movies, gaming',
    metrics: {
      contrast: 100,
      brightness: 70,
      color: 95,
    },
  },
  {
    id: 'qd-oled',
    name: 'QD-OLED',
    description: 'OLED enhanced with Quantum Dots',
    pros: ['Best color accuracy', 'Brighter than OLED', 'Perfect blacks', 'No burn-in'],
    cons: ['Most expensive', 'Limited availability'],
    priceRange: { min: 1500, max: 4500 },
    bestFor: 'Ultimate picture quality seekers',
    metrics: {
      contrast: 100,
      brightness: 90,
      color: 100,
    },
  },
  {
    id: 'mini-led',
    name: 'Mini-LED',
    description: 'Thousands of tiny LEDs for better control',
    pros: ['Very bright', 'Great contrast', 'No burn-in', 'Good value'],
    cons: ['Some blooming', 'Not as good as OLED blacks'],
    priceRange: { min: 700, max: 2500 },
    bestFor: 'Bright rooms, HDR content, gaming',
    metrics: {
      contrast: 85,
      brightness: 95,
      color: 90,
    },
  },
  {
    id: 'qled',
    name: 'QLED',
    description: 'Quantum Dot enhanced LED',
    pros: ['Very bright', 'Good colors', 'Affordable', 'No burn-in'],
    cons: ['Poor black levels', 'Limited viewing angles'],
    priceRange: { min: 300, max: 1500 },
    bestFor: 'Bright rooms, budget conscious',
    metrics: {
      contrast: 60,
      brightness: 90,
      color: 80,
    },
  },
  {
    id: 'led',
    name: 'LED',
    description: 'Traditional LCD with LED backlight',
    pros: ['Most affordable', 'Reliable', 'Energy efficient'],
    cons: ['Basic picture quality', 'Poor contrast', 'Limited colors'],
    priceRange: { min: 150, max: 600 },
    bestFor: 'Basic viewing, tight budgets',
    metrics: {
      contrast: 40,
      brightness: 75,
      color: 60,
    },
  },
];

export const roomDesigns: Room[] = [
  {
    id: 'modern-minimal',
    name: 'Sleek Modern Living Room with Hidden TV',
    style: 'modern',
    description: 'Clean lines meet cutting-edge tech. This serene space centers around the stunning Samsung S90D OLED.',
    totalBudget: 2800,
    featuredTV: tvDeals[1], // Samsung S90D OLED
    furniture: [
      { id: 'sofa-1', name: 'Rivet Revolve Modern Sofa', price: 899, category: 'seating', affiliateUrl: `https://www.amazon.com/dp/B07DHP6ZGY?tag=${AFFILIATE_TAG}` },
      { id: 'lamp-1', name: 'Brightech Sky LED Arc Lamp', price: 129, category: 'lighting', affiliateUrl: `https://www.amazon.com/dp/B01A8FIQK8?tag=${AFFILIATE_TAG}` },
      { id: 'table-1', name: 'Nathan James Theo Coffee Table', price: 249, category: 'tables', affiliateUrl: `https://www.amazon.com/dp/B07HKK9ZPX?tag=${AFFILIATE_TAG}` },
    ],
    saves: 12300,
  },
  {
    id: 'cozy-cottage',
    name: 'Warm & Cozy TV Room for Family Movie Nights',
    style: 'cozy',
    description: 'Warm and inviting space perfect for movie nights. Features the incredible Sony BRAVIA 8 OLED.',
    totalBudget: 3200,
    featuredTV: tvDeals[2], // Sony BRAVIA 8
    furniture: [
      { id: 'sofa-2', name: 'Stone & Beam Lauren Sofa', price: 1095, category: 'seating', affiliateUrl: `https://www.amazon.com/dp/B072QTNWL3?tag=${AFFILIATE_TAG}` },
      { id: 'lamp-2', name: 'DEWENWILS Table Lamp Set', price: 89, category: 'lighting', affiliateUrl: `https://www.amazon.com/dp/B07L8R5678?tag=${AFFILIATE_TAG}` },
      { id: 'table-2', name: 'Walker Edison Modern Farmhouse Table', price: 289, category: 'tables', affiliateUrl: `https://www.amazon.com/dp/B07MX2NYBF?tag=${AFFILIATE_TAG}` },
    ],
    saves: 18700,
  },
  {
    id: 'budget-modern',
    name: 'Minimalist Apartment Living Room Under $2K',
    style: 'minimal',
    description: 'Amazing value without compromise. The TCL QM8 Mini-LED delivers premium features at a great price.',
    totalBudget: 1600,
    featuredTV: tvDeals[3], // TCL QM8
    furniture: [
      { id: 'sofa-3', name: 'Zinus Jackie Classic Sofa', price: 379, category: 'seating', affiliateUrl: `https://www.amazon.com/dp/B078GQHT5J?tag=${AFFILIATE_TAG}` },
      { id: 'lamp-3', name: 'LEPOWER Wood Tripod Lamp', price: 59, category: 'lighting', affiliateUrl: `https://www.amazon.com/dp/B073W4HY5K?tag=${AFFILIATE_TAG}` },
      { id: 'table-3', name: 'Furinno Simple Design Table', price: 99, category: 'tables', affiliateUrl: `https://www.amazon.com/dp/B004M5BGD8?tag=${AFFILIATE_TAG}` },
    ],
    saves: 28100,
  },
  {
    id: 'gaming-paradise',
    name: 'RGB Gaming Room Setup with OLED Display',
    style: 'modern',
    description: 'Built for gamers. The LG C4 OLED with 120Hz and G-Sync delivers the ultimate gaming experience.',
    totalBudget: 2200,
    featuredTV: tvDeals[0], // LG C4 OLED
    furniture: [
      { id: 'sofa-4', name: 'GTRACING Gaming Sofa', price: 499, category: 'seating', affiliateUrl: `https://www.amazon.com/dp/B088KXCSJN?tag=${AFFILIATE_TAG}` },
      { id: 'lamp-4', name: 'Govee Immersion LED Light Bars', price: 149, category: 'lighting', affiliateUrl: `https://www.amazon.com/dp/B09CLP9DXC?tag=${AFFILIATE_TAG}` },
      { id: 'table-4', name: 'Rolanstar Coffee Table with LED', price: 189, category: 'tables', affiliateUrl: `https://www.amazon.com/dp/B099K2RWKY?tag=${AFFILIATE_TAG}` },
    ],
    saves: 16200,
  },
  {
    id: 'luxury-theater',
    name: 'Luxury Home Theater with 75" Screen',
    style: 'luxury',
    description: 'No compromise home theater. The massive Hisense U8N 75" Mini-LED creates a true cinema experience.',
    totalBudget: 3500,
    featuredTV: tvDeals[4], // Hisense U8N 75"
    furniture: [
      { id: 'sofa-5', name: 'Ashley Furniture Signature Sectional', price: 1299, category: 'seating', affiliateUrl: `https://www.amazon.com/dp/B07J5S888Y?tag=${AFFILIATE_TAG}` },
      { id: 'lamp-5', name: 'Philips Hue Go Portable Light', price: 159, category: 'lighting', affiliateUrl: `https://www.amazon.com/dp/B08G4DQWDS?tag=${AFFILIATE_TAG}` },
      { id: 'table-5', name: 'WLIVE LED Coffee Table', price: 279, category: 'tables', affiliateUrl: `https://www.amazon.com/dp/B0B1HQSG5K?tag=${AFFILIATE_TAG}` },
    ],
    saves: 9200,
  },
  {
    id: 'small-space',
    name: 'Small Apartment Living Room TV Setup',
    style: 'minimal',
    description: 'Perfect for apartments. The Amazon Fire TV Omni QLED combines great picture quality with Alexa integration.',
    totalBudget: 1100,
    featuredTV: tvDeals[5], // Amazon Fire TV Omni
    furniture: [
      { id: 'sofa-6', name: 'DHP Emily Futon Couch', price: 299, category: 'seating', affiliateUrl: `https://www.amazon.com/dp/B01M0A4B9M?tag=${AFFILIATE_TAG}` },
      { id: 'lamp-6', name: 'TaoTronics LED Desk Lamp', price: 39, category: 'lighting', affiliateUrl: `https://www.amazon.com/dp/B07CWLBVL7?tag=${AFFILIATE_TAG}` },
      { id: 'table-6', name: 'VASAGLE Nesting Coffee Table', price: 129, category: 'tables', affiliateUrl: `https://www.amazon.com/dp/B07K8TJ3R6?tag=${AFFILIATE_TAG}` },
    ],
    saves: 34300,
  },
  
];